### ISSUE TITLE
Issues with training the RecExplainer model in the run file train.sh

### ISSUE THREAD

**Issue by YuChenfu1022** [microsoft/RecAI#76]
hello, when I run the file train.sh in RecExplainer, that is, run the following code from sft_training.py
```
train_result = trainer.train(resume_from_checkpoint=checkpoint)
```
the following happens:
```
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [64,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [65,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [66,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [67,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [68,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905971214/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [31,0,0], thread: [69,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
```
at the end, it also appears:
```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Is there a format problem in the dataset for training RecExplainer? Have you encountered this issue when training RecExplainer? This issue has troubled me for several days.

**Comment by Micheallei** [comment]
In fact, I encountered this problem when I first wrote the code. The reason for this problem should be that an index error occurred when accessing tensor. But I think I should have solved this problem.
If you still encounter this problem, here are several steps to try to troubleshoot this problem
1. Make sure that the versions of packages such as torch and transformers in the conda environment are consistent with ours.
2. Whether additional data is introduced or hyperparameters are changed during the whole pipeline.
3. Try to locate which specific data caused this error and print it out. I guess a possible location that may cause this error is in `RecAI/RecExplainer/src/LLM4Exp.py`, line 145-146: 
`blank_embeds[user_pos] += user_embeds * filter_user`
`blank_embeds[item_pos] += item_embeds * filter_item`

Hopefully these suggestions will help you. If you still have problems, please feel free to discuss further.

**Comment by YuChenfu1022** [comment]
Thank you, according to your suggestion, I found that there was indeed a problem in this last step. I found that the size of `blank_embeds` is [4096, 4096], but the values ​​in `user_pos` and `item_pos` exceed 4096, which causes the label to be out of bounds. I still don’t understand how to get `user_pos` and `item_pos` during training, or how to avoid this situation.

**Comment by Micheallei** [comment]
In RecAI/RecExplainer/src/dataset/train_dataset.py, lines 299-306, 384-392, 477-492, we use tokenizer.additional_special_tokens_ids to get the position of the user token or item token in the token sequence of each sample in the mini-batch. 

In RecAI/RecExplainer/src/dataset/data_collator.py lines 19-20, 25-26, we calculate the global position of the user token in the mini-batch, that is, the positions of the user tokens after concatenating the token sequences of all samples (the same applies to item tokens).

Hopefully this explanation will help you further locate which text sample caused the error.

**Comment by YuChenfu1022** [comment]
Thanks, I found the cause of the error. I used two GPUs for training, when the `input_ids` generated in `RecAI/RecExplainer/src/dataset/data_collator.py` was used as a parameter input in line 131 of `RecAI/RecExplainer/src/LLM4Exp.py`, it would be split into two lists and trained on two GPUs respectively, which would cause an out-of-bounds phenomenon.

I guess it may be because I modified the training shell command in `train.sh`. I did not use the `torchrun` command to train the model, but changed it to `python sft_training.py` to start, and changed some parameters to the following:
```
python sft_training.py --seed 2024 \
    --do_train \
    --do_eval \
    --bf16 \
    --attn_implementation $attn_implementation \
    --rec_model_name_or_path $rec_model_name_or_path \
    --model_name_or_path $model_name_or_path \
    --model_max_length $model_max_length \
    --cache_dir $HOME/.cache \
    --torch_dtype $torch_dtype \
    --train_file $train_file \
    --validation_file $validation_file \
    --sequential_file $sequential_file \
    --max_hist_len $max_hist_len \
    --task_type $task_type \
    --template_name $template_name \
    --rec_model_type $rec_model_type \
    --output_dir $output_dir \
    --learning_rate 1e-4 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 1 \
    --dataloader_drop_last False \
    --dataloader_num_workers 4 \
    --gradient_accumulation_steps 4 \
    --weight_decay 0.0 \
    --warmup_ratio 0.1 \
    --logging_steps 100 \
    --save_strategy epoch \
    --evaluation_strategy epoch \
    --report_to wandb \
```

**Comment by Micheallei** [comment]
Multi-gpu training needs to be started using `torchrun`. It seems that there is no problem with other parameters.

If you run it well, I will close this issue.

**Comment by YuChenfu1022** [comment]
When I use `torchrun `for training, `CUDA out of memory` appears. When I reduce `per_device_train_batch_size` to 1, `CUDA out of memory` also appears. Is there any other way to solve it? I was using two `RTX 4090`.

**Comment by Micheallei** [comment]
There are many ways to solve this problem
1. Use a smaller model (such as the phi3 series)
2. Modify `r` and `target_modules` in RecAI/RecExplainer/src/sft_training.py line372-380 to reduce trainable parameters
3. Use gradient checkpointing
4. Use deepspeed zero

The first two methods should be able to run directly with minimal changes. The latter two methods may be incompatible with the current implementation of our model and require some modifications.
